import { useState } from 'react'
import type {
  GoalWithProgress,
  MaterialKind,
  MaterialSectionDraft,
  MaterialWithPace,
  UnitKind
} from '@shared/types'
import { UNIT_LABELS } from '@shared/types'
import { formatMinutes } from '@shared/time'
import { api, report, showToast, useLive } from '../api'

/**
 * The study materials attached to a goal: a course to work through, a book to
 * read. Everything the user has to decide is here; the day-to-day is a task
 * like any other, generated by the scheduler.
 */
export function MaterialsCard({ goal }: { goal: GoalWithProgress }): React.JSX.Element {
  const [materials] = useLive(() => api.invoke('materials:forGoal', goal.id), [], [goal.id])
  const [adding, setAdding] = useState<MaterialKind | null>(null)
  const [editingId, setEditingId] = useState<string | null>(null)

  return (
    <section className="card">
      <div className="card__title">
        Tài liệu học
        <span className="spacer" />
        {adding === null && (
          <>
            <button type="button" className="btn btn--sm" onClick={() => setAdding('course')}>
              + Khoá học
            </button>
            <button type="button" className="btn btn--sm" onClick={() => setAdding('book')}>
              + Sách
            </button>
          </>
        )}
      </div>

      {materials.length === 0 && adding === null && (
        <p className="small muted">
          Dán link khoá học hoặc chọn file sách, cho biết ngày phải xong — mỗi ngày app tự
          chia phần của ngày đó và nhắc bạn đúng giờ.
        </p>
      )}

      <div className="stack" style={{ gap: 12 }}>
        {materials.map((material) =>
          editingId === material.id ? (
            <MaterialForm
              key={material.id}
              goal={goal}
              material={material}
              kind={material.kind}
              onDone={() => setEditingId(null)}
            />
          ) : (
            <MaterialRow
              key={material.id}
              material={material}
              onEdit={() => setEditingId(material.id)}
            />
          )
        )}

        {adding !== null && (
          <MaterialForm goal={goal} kind={adding} onDone={() => setAdding(null)} />
        )}
      </div>
    </section>
  )
}

function unitWord(kind: UnitKind): string {
  return UNIT_LABELS[kind].many
}

const DAY_NAMES = ['T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'CN']

function describeDays(weekdays: number[]): string {
  if (weekdays.length === 0 || weekdays.length === 7) return 'Mỗi ngày'
  if (weekdays.length === 5 && weekdays.every((d) => d < 5)) return 'T2–T6'
  return [...weekdays].sort((a, b) => a - b).map((d) => DAY_NAMES[d]).join(', ')
}

function MaterialRow({
  material,
  onEdit
}: {
  material: MaterialWithPace
  onEdit: () => void
}): React.JSX.Element {
  const { pace } = material
  const total = material.totalUnits - material.unitsDoneBefore
  const percent = total > 0 ? Math.round((material.unitsDone / total) * 100) : 0
  const finished = pace.remainingUnits === 0

  function open(): void {
    if (material.url) void api.invoke('app:openExternal', material.url).catch(report)
    else if (material.filePath) void api.invoke('app:openPath', material.filePath).catch(report)
  }

  return (
    <div className="material">
      <div className="material__head">
        <span className="material__title">{material.title}</span>
        <span className="chip">{material.kind === 'book' ? 'sách' : 'khoá học'}</span>
        {(material.url || material.filePath) && (
          <button type="button" className="btn btn--primary btn--sm" onClick={open}>
            Mở
          </button>
        )}
        <button type="button" className="btn btn--sm" onClick={onEdit}>
          Sửa
        </button>
      </div>

      <div className="progress">
        <span style={{ width: `${percent}%` }} />
      </div>

      <div className="row row--wrap small muted">
        <span>
          {material.unitsDone}/{total} {unitWord(material.unitKind)}
        </span>
        <span>· {percent}%</span>
        <span>· {describeDays(material.weekdays)}</span>
        {material.studyTime && <span>· {material.studyTime}</span>}
      </div>

      {finished ? (
        <span className="chip chip--accent">Đã học xong — không sinh task nữa</span>
      ) : (
        <span className="chip chip--accent">
          Hôm nay: {pace.unitsToday} {unitWord(material.unitKind)} ({pace.unitFrom}–{pace.unitTo})
          {pace.minutesToday != null ? ` · ${formatMinutes(pace.minutesToday)}` : ''}
        </span>
      )}

      {pace.overloaded && (
        <span className="chip chip--warn">
          Quá tải: tối đa {material.maxUnitsPerDay} {unitWord(material.unitKind)}/ngày thì
          {pace.projectedFinishDay ? ` sớm nhất ${pace.projectedFinishDay}` : ' không kịp'} — cân
          nhắc dời hạn
        </span>
      )}
    </div>
  )
}

function MaterialForm({
  goal,
  material,
  kind,
  onDone
}: {
  goal: GoalWithProgress
  material?: MaterialWithPace
  kind: MaterialKind
  onDone: () => void
}): React.JSX.Element {
  const [title, setTitle] = useState(material?.title ?? '')
  const [url, setUrl] = useState(material?.url ?? '')
  const [filePath, setFilePath] = useState(material?.filePath ?? '')
  const [unitKind, setUnitKind] = useState<UnitKind>(
    material?.unitKind ?? (kind === 'book' ? 'page' : 'lesson')
  )
  const [totalUnits, setTotalUnits] = useState(String(material?.totalUnits ?? ''))
  const [doneBefore, setDoneBefore] = useState(String(material?.unitsDoneBefore ?? 0))
  const [minutesPerUnit, setMinutesPerUnit] = useState(
    material?.minutesPerUnit != null ? String(material.minutesPerUnit) : ''
  )
  const [weekdays, setWeekdays] = useState<number[]>(material?.weekdays ?? [0, 1, 2, 3, 4])
  const [studyTime, setStudyTime] = useState(material?.studyTime ?? '20:00')
  const [maxPerDay, setMaxPerDay] = useState(
    material?.maxUnitsPerDay != null ? String(material.maxUnitsPerDay) : ''
  )
  const [targetDate, setTargetDate] = useState(material?.targetDate ?? goal.targetDate ?? '')
  const [sections, setSections] = useState<MaterialSectionDraft[]>(
    material?.sections.map((s) => ({ title: s.title, startUnit: s.startUnit, endUnit: s.endUnit })) ??
      []
  )
  const [picked, setPicked] = useState(false)

  function pickFile(): void {
    void api
      .invoke('materials:pickFile')
      .then((file) => {
        if (!file) return
        setFilePath(file.filePath)
        setPicked(true)
        if (!title.trim()) setTitle(file.title)
        if (file.sections.length > 0) setSections(file.sections)
        if (file.pageCount > 0 && unitKind === 'page') setTotalUnits(String(file.pageCount))
        if (file.pageCount > 0 && unitKind === 'chapter' && file.sections.length > 0) {
          setTotalUnits(String(file.sections.length))
        }
      })
      .catch(report)
  }

  function toggleDay(index: number): void {
    setWeekdays((days) =>
      days.includes(index) ? days.filter((d) => d !== index) : [...days, index].sort()
    )
  }

  function submit(event: React.FormEvent): void {
    event.preventDefault()
    const total = Number(totalUnits)
    if (!title.trim() || !Number.isFinite(total) || total <= 0) {
      showToast('Cần tên và tổng số ' + unitWord(unitKind))
      return
    }

    const draft = {
      goalId: goal.id,
      kind,
      title: title.trim(),
      url: url.trim() || null,
      filePath: filePath.trim() || null,
      unitKind,
      totalUnits: Math.round(total),
      unitsDoneBefore: Math.max(0, Math.round(Number(doneBefore) || 0)),
      minutesPerUnit: minutesPerUnit ? Math.round(Number(minutesPerUnit)) : null,
      weekdays,
      studyTime: studyTime || null,
      maxUnitsPerDay: maxPerDay ? Math.round(Number(maxPerDay)) : null,
      targetDate: targetDate || null,
      sections
    }

    const request = material
      ? api.invoke('materials:update', material.id, draft)
      : api.invoke('materials:create', draft)
    void request.then(() => onDone()).catch(report)
  }

  return (
    <form className="material material--form stack" onSubmit={submit}>
      <div className="card__title">
        {material ? 'Sửa' : kind === 'book' ? 'Sách mới' : 'Khoá học mới'}
      </div>

      <div className="field-grid">
        <label className="field">
          <span className="field__label">Tên</span>
          <input
            className="input input--inline"
            autoFocus
            placeholder={kind === 'book' ? 'Clean Code' : 'Machine Learning'}
            value={title}
            onChange={(e) => setTitle(e.target.value)}
          />
        </label>
        <label className="field">
          <span className="field__label">Link</span>
          <input
            className="input input--inline"
            placeholder="https://coursera.org/learn/…"
            value={url}
            onChange={(e) => setUrl(e.target.value)}
          />
        </label>
        <div className="field">
          <span className="field__label">File</span>
          <div className="row">
            <button type="button" className="btn btn--sm" onClick={pickFile}>
              Chọn file…
            </button>
            {filePath && <span className="small muted ellipsis">{filePath.split('/').pop()}</span>}
          </div>
          {picked && (
            <span className="field__hint">
              {sections.length > 0
                ? `Đọc được ${sections.length} chương từ mục lục PDF`
                : 'PDF này không có mục lục — nhập chương bên dưới, hoặc cứ chia theo tổng số trang'}
            </span>
          )}
        </div>
      </div>

      <div className="field-grid">
        {kind === 'book' && (
          <label className="field">
            <span className="field__label">Đơn vị</span>
            <select
              className="select input--inline"
              value={unitKind}
              onChange={(e) => setUnitKind(e.target.value as UnitKind)}
            >
              <option value="page">Trang</option>
              <option value="chapter">Chương</option>
            </select>
          </label>
        )}
        <label className="field">
          <span className="field__label">Tổng số {unitWord(unitKind)}</span>
          <input
            className="input input--inline"
            inputMode="numeric"
            value={totalUnits}
            onChange={(e) => setTotalUnits(e.target.value)}
          />
        </label>
        <label className="field">
          <span className="field__label">Đã xong trước đó</span>
          <input
            className="input input--inline"
            inputMode="numeric"
            value={doneBefore}
            onChange={(e) => setDoneBefore(e.target.value)}
          />
        </label>
        <label className="field">
          <span className="field__label">Phút mỗi {UNIT_LABELS[unitKind].one}</span>
          <input
            className="input input--inline"
            inputMode="numeric"
            placeholder="15"
            value={minutesPerUnit}
            onChange={(e) => setMinutesPerUnit(e.target.value)}
          />
        </label>
        <label className="field">
          <span className="field__label">Giờ học</span>
          <input
            className="input input--inline"
            type="time"
            value={studyTime}
            onChange={(e) => setStudyTime(e.target.value)}
          />
        </label>
        <label className="field">
          <span className="field__label">Tối đa mỗi ngày</span>
          <input
            className="input input--inline"
            inputMode="numeric"
            placeholder="không giới hạn"
            value={maxPerDay}
            onChange={(e) => setMaxPerDay(e.target.value)}
          />
          <span className="field__hint">Vượt ngưỡng này thì app báo deadline không khả thi</span>
        </label>
        <label className="field">
          <span className="field__label">Phải xong ngày</span>
          <input
            className="input input--inline"
            type="date"
            value={targetDate}
            onChange={(e) => setTargetDate(e.target.value)}
          />
          <span className="field__hint">Bỏ trống = theo hạn của goal</span>
        </label>
      </div>

      <div className="field">
        <span className="field__label">Ngày học trong tuần</span>
        <div className="row row--wrap">
          {DAY_NAMES.map((name, index) => (
            <button
              key={name}
              type="button"
              className="pick"
              aria-pressed={weekdays.includes(index)}
              onClick={() => toggleDay(index)}
            >
              {name}
            </button>
          ))}
        </div>
      </div>

      <SectionEditor unitKind={unitKind} sections={sections} onChange={setSections} />

      <div className="row">
        <button type="submit" className="btn btn--primary btn--sm">
          {material ? 'Lưu' : 'Thêm'}
        </button>
        <button type="button" className="btn btn--sm" onClick={onDone}>
          Huỷ
        </button>
        {material && (
          <>
            <span className="spacer" />
            <button
              type="button"
              className="btn btn--danger btn--sm"
              onClick={() => {
                void api
                  .invoke('materials:delete', material.id)
                  .then(() => {
                    showToast('Đã xoá tài liệu')
                    onDone()
                  })
                  .catch(report)
              }}
            >
              Xoá
            </button>
          </>
        )}
      </div>
    </form>
  )
}

/** The table of contents, editable whether it came from a PDF or from memory. */
function SectionEditor({
  unitKind,
  sections,
  onChange
}: {
  unitKind: UnitKind
  sections: MaterialSectionDraft[]
  onChange: (sections: MaterialSectionDraft[]) => void
}): React.JSX.Element {
  function patch(index: number, next: Partial<MaterialSectionDraft>): void {
    onChange(sections.map((section, i) => (i === index ? { ...section, ...next } : section)))
  }

  return (
    <div className="field">
      <span className="field__label">Mục lục ({sections.length} mục)</span>
      <div className="stack" style={{ gap: 4 }}>
        {sections.map((section, index) => (
          <div key={index} className="row">
            <input
              className="input input--inline"
              value={section.title}
              onChange={(e) => patch(index, { title: e.target.value })}
            />
            <input
              className="input input--inline"
              style={{ width: 74 }}
              inputMode="numeric"
              value={section.startUnit}
              onChange={(e) => patch(index, { startUnit: Number(e.target.value) || 0 })}
            />
            <input
              className="input input--inline"
              style={{ width: 74 }}
              inputMode="numeric"
              value={section.endUnit}
              onChange={(e) => patch(index, { endUnit: Number(e.target.value) || 0 })}
            />
            <button
              type="button"
              className="icon-btn"
              title="Xoá mục"
              onClick={() => onChange(sections.filter((_, i) => i !== index))}
            >
              ×
            </button>
          </div>
        ))}
      </div>
      <button
        type="button"
        className="btn btn--sm"
        style={{ alignSelf: 'flex-start', marginTop: 6 }}
        onClick={() =>
          onChange([
            ...sections,
            {
              title: `Chương ${sections.length + 1}`,
              startUnit: (sections[sections.length - 1]?.endUnit ?? 0) + 1,
              endUnit: (sections[sections.length - 1]?.endUnit ?? 0) + 1
            }
          ])
        }
      >
        + Thêm mục
      </button>
      <span className="field__hint">
        Tên · {UNIT_LABELS[unitKind].one} bắt đầu · {UNIT_LABELS[unitKind].one} kết thúc. Bỏ trống
        cũng được — app vẫn chia đều theo tổng số.
      </span>
    </div>
  )
}
